name: Lighthouse CI Audit

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lighthouse on brooksrunning.com
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 'https://www.brooksrunning.com'
          uploadArtifacts: true
          temporaryPublicStorage: true
