name: Lighthouse Audit

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:  # Manual run via GitHub UI

  schedule:           # Nightly run (adjust time as needed)
    - cron: "0 7 * * *"  # Every day at 7 AM UTC

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Serve production build
        run: |
          yarn global add serve
          serve -s build -l 3000 &
          npx wait-on http://localhost:3000

      - name: Run Lighthouse audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: http://localhost:3000
          uploadArtifacts: true
          temporaryPublicStorage: true
