name: Lighthouse Audit for BrooksRunning

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:        # Allows manual run

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (no repo needed, just placeholder)
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y libatk-bridge2.0-0 libgtk-3-0 libgbm-dev
          npm install -g lighthouse jq

      - name: Run Lighthouse on brooksrunning.com
        run: |
          lighthouse https://www.brooksrunning.com \
            --quiet \
            --chrome-flags="--headless" \
            --output=json \
            --output-path=report.json

      - name: Print key Lighthouse scores
        run: |
          echo "=== Lighthouse Scores for https://www.brooksrunning.com ==="
          cat report.json | jq '.categories | {
            performance: .performance.score,
            accessibility: .accessibility.score,
            best_practices: ."best-practices".score,
            seo: .seo.score
          }'
