name: PageSpeed Monitoring

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  run-pagespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run PageSpeed script with debug logging
        env:
          API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
        run: |
          python pagespeed_logger.py
          echo "=== Current CSV content ==="
          cat pagespeed_scores.csv
          echo "=== End CSV content ==="

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git stash push -m "stash before pull" || echo "Nothing to stash"
          git pull --rebase origin master
          git stash pop || echo "No stash to pop"
          git add pagespeed_scores.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update PageSpeed scores $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin master
          else
            echo "No changes to commit"
          fi

