name: Weekly Web Vitals Report

on:
  schedule:
    - cron: '0 10 * * 1'  # Every Monday 10:00 UTC
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests matplotlib seaborn

      - name: Run weekly report script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          CRUX_API: ${{ secrets.CRUX_API }}
        run: python weekly_web_vitals.py
